### ISSUE TITLE
Ordinal Evaluation

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#141] opened 2016-08-16 10:01 UTC
Instead of asking participants for each discrete rating, can we have some view that would allow users to rank samples in some order - eg. 

X is first 
Y is second 
R is third

Maybe this would be constraints on Radio boxes, maybe it would be a modification of APE, where the sliders are 1/n the width of the bar (where n is the number of samples) and then as each one is moved, the others are reallocated to the correct position?

**Comment by nickjillings** [comment] 2016-08-16 10:04
I think it's probably a rotational view of the radio / discrete option. Just needs a bit more coding to disable row and column of clicked. For instance, right now you could rank all radio as 1's, but locking it by column as well then only one track could be given a 1 value.

Equally it could be a modification of the Vertical/Horizontal sliders where they snap to discrete steps giving an easier visual guide.

Combined perhaps with the 'order by preference' bug #119 which would allow users to quickly view their selection in a ranked order.

**Comment by BrechtDeMan** [comment] 2016-08-16 10:12
I like both, though the visual ranking is definitely more intuitive (i.e. APE style dragging where sliders snap into positions as you drag). 

Excessive constraints on the radio buttons might get overwhelming and unclear.

**Comment by nickjillings** [comment] 2016-08-16 10:54
Agreed, thinking about it would be easy to get into an un-moveable (that reads right..) state where, say 4 tracks are ranked 1,2,3,4. It would then be impossible to move them since the interface may say 'well, you've already got a file in that position'. So could get tricky quickly.

Perhaps an APE system where the divisions on the axis are clearly marked for individual points and automatic highlighting of sliders which are in the same group?

Otherwise could be an interface where the sliders are 'outside' and you drag them into an order, automatically moving round to meet the ranking. For instance if I have 4 tracks and have ranked 3 of them (so we have 1,2,3) the fourth could be dropped at the start and would generate a new 'slot' for it and push all the others up one? Or dragged between 2 and 3, only pushing 3 up to position 4? Does that make sense? May be a little easier as well to move round since it's a case of dragging it into the new position between fragments.

Would also be very intuitive for touch users

**Comment by BrechtDeMan** [comment] 2017-03-27 12:32
Bump! Received another request for this functionality. 

Too simple not too have.

**Comment by nickjillings** [comment] 2017-04-25 12:24
Starting this

**Comment by nickjillings** [comment] 2017-04-25 14:41
Working example now up on: http://dmtlab.bcu.ac.uk/nickjillings/waet-dev/test.html?url=tests/examples/ordinal_example.xml

**Comment by BrechtDeMan** [comment] 2017-04-25 19:03
Still somewhat buggy, sometimes dragging works but sometimes ordering remains the same. Can't quite figure out what affects it, e.g. playing or not, distance dragged, exact position where dropped, ...

**Comment by nickjillings** [comment] 2017-04-26 10:20
Can you let me know on what browser this happened with as it is smooth for me. You should hover it over the position you want it to be in and it will then appear there 'ghosted' until dropped in place.

Play state has no impact on dragging (or shouldn't).

**Comment by BrechtDeMan** [comment] 2017-07-17 18:36
This still doesn't work at all for me. Moving all over the place, including markers that weren't selected and not even adjacent. Chrome v59 (up to date), the link above. 
Works like a charm in Firefox though.

**Comment by nickjillings** [comment] 2017-08-02 10:47
Confirmed working in Safari (10.1.2), Chrome (59.0.3071) and Firefox (54.0.1)

**Comment by BrechtDeMan** [comment] 2017-10-08 15:16
Still doesn't work on Safari (10.1.2) or Chrome (61.0.3163.100) - see GIF or try on http://webprojects.eecs.qmul.ac.uk/bdm30/master/test.html?url=tests/examples/ordinal_example.xml 

![waet-ordinal-bug](https://user-images.githubusercontent.com/4103243/31318049-20c07d56-ac4c-11e7-861a-755af6045790.gif)

**Comment by nickjillings** [comment] 2017-10-31 10:28
Starting this now, here is the checklist of browsers as it stands:

- Firefox v56.0 (Linux/Ubuntu) Working, but layout issues
- Firefox v56.0.2 (Win10, OSX 10.11.6) Working
- Firefox v57.0b12 (Win10) Working
- Chrome 61.0.3163.100 (Win10, OSX 10.11.6) Fail
- Edge 40.15063.674.0 (Win10) Fail
- Safari 11.0 (OSX 10.11.6) Fail

So it does seem that the behaviour is only working in Firefox, but thankfully all the other browsers are failing the same way, which means that there should be a one-fix-all solution

**Comment by nickjillings** [comment] 2017-10-31 10:57
Fixed in f94c732

Turns out it is a simple specification failure. It appears only Firefox works with the dataTransfer object, so now it is using session-storage as fallback. Amazingly though, Firefox then didn't work when the dataTransfer wasn't set!

So hopefully this is now resolved and as long as browsers completely support the standard when they implement it, it should be fine.

**Closed by nickjillings** 2017-10-31 10:57 UTC
Labels: enhancement, in progress, review
