### ISSUE TITLE
ref="null" saves

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#143] opened 2016-08-25 12:49 UTC
Hey,

I am getting some issues, where saves and refKey have null values.
Do you know what could be causing this?

**Comment by nickjillings** [comment] 2016-09-02 10:47
Usually these are caused by an invalid save, however they usually have no data associated with them. If yours have data, it may be possible to re-link using the timestamps.

There are checks to ensure that a 'null' does not happen, will investigate and strengthen these possible points

**Comment by nickjillings** [comment] 2016-09-22 11:28
This should now be caught so that, in the event of a key=="null" the session will not post to the server. This was being caused at the end where a separate uploading script was being used which bypassed the checks for a valid key. Now it should never be possible to save with key being "null" and any event of that occurring should show the "please email this" message with a local saving.

I've still yet to find why a key of "null" is being created anyway, usually this is because the server either never responded with an 'OK to use that key', related probably to some issues in #150 where the server responds malformed data, or it just ignores and the system continuously retries.

I think I will reverse the keygen process so that the client requests a key and the server generates one. My concern for this was a possible race-condition where two identical keys are made at the same time which could lead to overwriting, however the chances are quite low especially if a good seed it used and it is based on some millisecond counter (to be fair this risk still exists now and is more likely if two machines request the same key at the same time).

**Comment by nickjillings** [comment] 2016-10-24 10:13
This has been fixed now in master

**Closed by nickjillings** 2016-10-24 10:13 UTC
Labels: bug, priority, urgent
