### ISSUE TITLE
pre and post surveys are a mandatory requirement for all questions

### ISSUE THREAD

**Issue by callumgoddard** [BrechtDeMan/WebAudioEvaluationTool#198] opened 2017-04-14 12:24 UTC
I'm working with the AB interface... but in my testing you can't make a listening test without having a survey element of some type where ever a survey option is given in the test create webpage. If any are left blank, the test will error when trying to run it.

I'd like to be able to have a statement at the start then allow each question to follow on from the next without any interruption, this currently isn't possible, and for simpler test results in participants being bombarded with a lot of popups.

**Comment by nickjillings** [comment] 2017-04-14 14:57
This is actually a bug in the test creator tool, reported in #183.

The test creator incorrectly creates an empty test node, which is currently not valid. A solution is to edit the XML directly and remove the survey nodes from each page. The survey holder nodes are not mandatory, but if there is one it is expected for it to hold some information.

I'll close this issue as it is a duplicate of #183. But thanks for highlighting, I'll raise the priority on this.

**Closed by nickjillings** 2017-04-14 14:57 UTC

**Comment by callumgoddard** [comment] 2017-04-14 15:01
Ah good it know its a known issue and priority is being raised. Thanks for the suggested fix via editing the xml.
