### ISSUE TITLE
Save problem

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#234] opened 2017-09-14 10:13 UTC
Not saved to server but presented locally instead. 

    core.js:3631Intermediate save: Error! undefined
    core.js:424 Save: Error! undefined

May be a permissions thing, or PHP? 

Newest master branch commit: webprojects.eecs.qmul.ac.uk/bdm30/master/test.html?url=tests/examples/APE_example.xml&saveFilenamePrefix=customname

**Comment by nickjillings** [comment] 2017-09-14 11:53
Think this is actually because of #235. The save works fine, since the requestKey.php creates the file to ensure that no two keys are created twice.

It's the saving of the files that causes a problem. The PHP server wants to expand the XML rather than just dump the file so it tries to open the keyfile.

**Comment by nickjillings** [comment] 2017-09-14 12:15
Closed as caused by #235

**Closed by nickjillings** 2017-09-14 12:15 UTC
