### ISSUE TITLE
popup warning should steal focus from "next" button

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#99] opened 2016-05-24 14:50 UTC
For instance, if a dialog saying "please enter a valid number" comes up, you should be able to dismiss it by pressing "enter". Currently, pressing enter will cause another  "please enter a valid number" to be stacked in the dialog (because the form is resubmitted), see here 

<img width="679" alt="screen shot 2016-05-24 at 15 48 26" src="https://cloud.githubusercontent.com/assets/4260604/15508391/2943145e-21c7-11e6-9521-edf007e0061d.png">

**Comment by nickjillings** [comment] 2016-05-24 14:52
Duplicate of #83

**Closed by nickjillings** 2016-05-24 14:52 UTC
Labels: duplicate
