### ISSUE TITLE
Safari (8.0.4) not working

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#21] opened 2016-04-19 09:36 UTC
Test with newest version (default/dev tip on 18 April 20:49 commit) works in Chrome but does not load in Safari, with error as below: 

[Error] TypeError: undefined is not an object (evaluating 'responseDocument.children[0]') 
	loadProjectSpecCallback _(core.js, line 205)_
	onload _(core.js, line 158)_

**Comment by nickjillings** [comment] 2016-04-19 09:58
Another user reported this yesterday as well, but I had tried it on my office iMac and it worked yesterday. Although it was doing updates last night so I will check if something has been changed there.

Can you confirm if Firefox for OSX is still working as well for me?

**Comment by BrechtDeMan** [comment] 2016-04-19 10:32
Yes, no issues on Firefox 42.0, Mac OS X.10.2!

**Comment by nickjillings** [comment] 2016-04-19 10:53
I may have posted a potential fix, however I could not replicate the bug at all. This may be a fixed issue (I'm on OSX 10.11.4). Apple only update the WebKit on OS changes, not Safari changes, since it considers WebKit a system code.

It seems strange that it has suddenly changed (that part of the code hasn't been touched recently).

If you still have problems can you copy your navigator.userAgent for me from the Browser console:

Confirmed working on:
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17"

**Comment by nickjillings** [comment] 2016-04-19 10:54
Also confirmed on Firefox 45.0

**Comment by BrechtDeMan** [comment] 2016-04-19 12:36
Still doesn't work but error has changed: 

[Error] TypeError: undefined is not an object (evaluating 'scaleParent.children.length')
	decode (specification.js, line 359)
	decode (specification.js, line 474)
	decode (specification.js, line 144)
	loadProjectSpecCallback (core.js, line 237)
	onload (core.js, line 158)

navigator.userAgent yields 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10"

**Comment by nickjillings** [comment] 2016-04-19 13:26
Can you send me your XML

**Comment by nickjillings** [comment] 2016-04-22 08:36
On this, can you confirm if this bug is still an issue? I know there is another for the surveys (and can you also confirm that one as well please).

**Comment by BrechtDeMan** [comment] 2016-04-22 11:36
Still an issue. 
Not sure what you mean by 'the surveys'?

**Comment by nickjillings** [comment] 2016-04-25 10:06
So you still get an issue with the scaleParent.children.length line?

In the surveys, you mentioned that no surveys were viewed, is this still the case?

**Comment by BrechtDeMan** [comment] 2016-04-25 11:24
Oh right, sorry - surveys work now. Post-page questions are shown, and after completing those you go back to the same page. Then clicking next again goes to the following page. Only in Safari. 

Getting this error upon submitting the last post-page survey question: 

[Error] TypeError: undefined is not an object (evaluating 'this.XMLDOM.children[0]')
	postResult (core.js, line 2904)
	proceedClicked (core.js, line 847)
	onclick (core.js, line 584)
	(anonymous function) (core.js, line 564)
	dispatch (jquery-2.1.4.js, line 4435)
	handle (jquery-2.1.4.js, line 4121)

Subsequently clicking 'Next' to actually move to the following page doesn't throw any errors.

**Comment by nickjillings** [comment] 2016-04-26 08:45
OK, it seems that Safari 8.0.4 does not support the 'children' method of the DOM tree (quite a fundamental HTML4 component though...). I will try and trim out as much as I can from the code.

**Comment by nickjillings** [comment] 2016-04-27 08:42
Some more fixes now, core.js does not reference .children at all. Haven't heard anything though as to why this is an issue in the first place as it is a pretty fundamental DOM method.

**Comment by BrechtDeMan** [comment] 2016-04-27 17:11
It would seem it's fixed now!

**Comment by nickjillings** [comment] 2016-04-29 13:58
OK, I'll close this now as any other bugs are more likely to be their own issues.

**Closed by nickjillings** 2016-04-29 13:58 UTC
Labels: bug, in progress, Safari, urgent
